### ISSUE TITLE
Free VDS for project

### ISSUE THREAD

**Issue by ekifox** [BlackEyePS/cms#1]
Hi, my name is Sergey, and i'm the DO fan from 2012 year (sounds like disease xD)
I can give one of my MS Azure VDS for project, if you want.

Sorry for mistakes, i'm not from English-speaking country.

**Comment by manulaiko** [comment]
Right now, BlackEye is pretty new even for an alpha version. Even if it were in a stable version, hosting it to the public would mean copyright issues.

This project is open-source under the GNU license, meaning that anyone is free to download the source and use it as he/she wants, of course, facing the consequences.

Anyways, thanks for the offer!
